### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by jasperpeeters** [bbc/nmos-auth-server#37]
I'm getting the following error when I try to startup the auth-server inside a docker environment:

```
root@69d3da24843a:/home/nmos-auth# /usr/bin/nmosauth
2020-05-07 07:10:31,807 : utils : DEBUG : Choosing interface from /etc/nmoscommon/config.json file: []
2020-05-07 07:10:31,807 : utils : DEBUG : Could not find ipp-utils, will try using default gateway interface
2020-05-07 07:10:31,807 : utils : DEBUG : Choosing interface using the default gateway: 172.17.0.2
WARNING:mdnsbridge:This class is deprecated. Please use the matching one in nmos-mdns-bridge instead.
Exception loading config: name 'f' is not defined
Traceback (most recent call last):
  File "/usr/bin/nmosauth", line 7, in <module>
    service.run()
  File "/usr/local/lib/python3.5/dist-packages/nmosauth/auth_server/security_service.py", line 107, in run
    self.start()
  File "/usr/local/lib/python3.5/dist-packages/nmosauth/auth_server/security_service.py", line 64, in start
    gevent.signal(signal.SIGINT, self.sig_handler)
TypeError: 'module' object is not callable
```

Steps to reproduce:
- Start docker (`docker run -it ubuntu`, also tried with 16.04: `docker run -it ubuntu:xenial`)
- Update packagemanager: `apt update && apt upgrade`
- Install required packages: `apt install python3 python3-pip git`
- Create working dir: `mkdir /home/nmos-auth` and `cd /home`
-  `git clone <this_repo> nmos-auth`
- Install with either method (e.g. `pip3 install . --no-binary nmos-auth`)
- Run with `/usr/bin/nmos-auth`
- See above error/output

Was somebody able to run this inside a container? I suspect that it runs inside a container is not the problem, but cannot say for sure ofc.

**Comment by andrewbonney** [comment]
I wonder if that's coming from here: https://github.com/bbc/nmos-auth-server/blob/master/nmosauth/auth_server/config.py#L39. Does it make a difference if you create the file at that path?

**Comment by jasperpeeters** [comment]
Negative
